version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    command: serve -s build -l 3000
    container_name: mern-client
    # ports:
    #   - '3000:3000'
    env_file:
      - ./.env
    restart: unless-stopped

  server:
    build: ./server # find Dokcerfile in this folder
    container_name: mern-server # server container name
    command: yarn start # run after Dockerfile finished
    restart: unless-stopped # restarts container on failure expect the container is stopped
    #ports:
    # - '3001:3001'                   # external:internal (machine:container) port
    env_file:
      - ./.env # env file path
    depends_on:
      - server_db # depends on data base

  nginx:
    image: nginx:alpine
    container_name: mern-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  server_db:
    image: mongo:latest # readt mongo db image (will download from docker hub)
    container_name: mern-db # data base name
    volumes:
      - mern_mongo_db:/data/db # don't rewrite always in build

volumes:
  mern_mongo_db: # for using volume in other projects
